### ISSUE TITLE
Task is skipping all files except SVG

### ISSUE THREAD

**Issue by rianverhagen** [GeenenTijd/grunt-tinyimg#2]
When running the task I get the following output:

Running "tinyimg:dynamic" (tinyimg) task
Skipped ../../public/static/img/background-blue.jpg [no savings]
Optimized ../../public/static/img/borders/bottom.svg [saved 99 % - 21.11 kB → 15 B]

It skips all jpg's and png's and updates all svg contents to [object Object].

Our Gruntfile contains this:

tinyimg: {
            dynamic: {
                files: [{
                  expand: true,
                  cwd: '../../public/static/img/',
                  src: ['*_/_.{png,jpg,svg}'],
                  dest: '../../public/static/img/optim/'
                }]
            }
        }

**Comment by GlennGeenen** [comment]
I updated the dependencies, new version is published. Can you update and test?

**Comment by rianverhagen** [comment]
Works like a charm! Thanks a lot!

**Comment by rianverhagen** [comment]
The issue with SVG's still persist.

**Comment by GlennGeenen** [comment]
I didn't check the SVG, my bad, it's fixed now, new version published.

**Comment by rianverhagen** [comment]
Thanks!
